prints out debug messages

diff --git a/ci/pipeline/pcf-usage-report-simple.yml b/ci/pipeline/pcf-usage-report-simple.yml
--- a/ci/pipeline/pcf-usage-report-simple.yml
+++ b/ci/pipeline/pcf-usage-report-simple.yml
@@ -16,14 +16,7 @@ resources:
     branch: master
     uri: {{git-project-url}}
     skip_ssl_verification: true
-- name: file-repository
-  type: s3
-  source:
-    bucket: {{s3-bucket}}
-    access_key_id: {{s3-access-key-id}}
-    secret_access_key: {{s3-secret-access-key}}
-    regexp: pcf-.*-usage-from-\d{4}-\d{2}-\d{2}-to-\d{4}-\d{2}-\d{2}_(.*).json
-    region_name: {{s3-region_name}}
+
 - name: send-email
   type: email
   source:
@@ -94,68 +87,18 @@ jobs:
       params:
         PCF_DEPLOY_NAME: {{pcf-deploy-name}}
 
-    - put: file-repository
-      params:
-        file: ./orgs-usage-consolidated/*.json
-        acl: public-read
-
-    on_failure:
-      put: send-email
-      params:
-        to: [ {{email-to}} ]
-        subject: ./email-text/email-subject-failure.txt
-        body: ./email-text/email-body-failure.txt
-
-
-- name: feed-report-into-billing-system
-  serial: true
-  public: true
-  plan:
-  - do:
-    - get: pipeline-scripts
-      trigger: false
-    - get: file-repository
-      trigger: true
-      passed:
-      - retrieve-and-process-pcf-usage-data
-
-    - task: prep-notification-email-text
-      file: pipeline-scripts/ci/tasks/prepare-email.yml
-      params:
-        PCF_DEPLOY_NAME: {{pcf-deploy-name}}
-
-    - task: feed-report-data-into-billing-system
-      config:
-        platform: linux
-        image_resource:
-          type: docker-image
-          source:
-            repository: pivotalservices/pcf-usage-tools
-            tag: "latest"
-        inputs:
-          - name: pipeline-scripts
-          - name: file-repository
-        run:
-          path: sh
-          args:
-          - -exc
-          - |
-            #!/bin/bash
-            set -e
-            echo "This is a place holder for the code to read the report file from the file repository and feed it to a billing system"
-            echo "JSON Report file URL from the repository:"
-            cat ./file-repository/url
-            echo "Report file version(timestamp of creation in seconds):"
-            cat ./file-repository/version
-            echo "File list available to be used by this job/task:"
-            ls -la file-repository
-
-
     - put: send-email
       params:
         to: [ {{email-to}} ]
-        subject: ./email-text/email-subject.txt
-        body: ./email-text/email-body.txt
+        subject_text: "PCF Usage Report"
+        body_text: "Here is your report."
+        attachments:
+          - ./orgs-usage-consolidated/*.json
+
+#    - put: file-repository
+#      params:
+#        file: ./orgs-usage-consolidated/*.json
+#        acl: public-read
 
     on_failure:
       put: send-email
@@ -163,3 +106,61 @@ jobs:
         to: [ {{email-to}} ]
         subject: ./email-text/email-subject-failure.txt
         body: ./email-text/email-body-failure.txt
+
+
+#- name: feed-report-into-billing-system
+#  serial: true
+#  public: true
+#  plan:
+#  - do:
+#    - get: pipeline-scripts
+#      trigger: false
+#    - get: file-repository
+#      trigger: true
+#      passed:
+#      - retrieve-and-process-pcf-usage-data
+#
+#    - task: prep-notification-email-text
+#      file: pipeline-scripts/ci/tasks/prepare-email.yml
+#      params:
+#        PCF_DEPLOY_NAME: {{pcf-deploy-name}}
+#
+#    - task: feed-report-data-into-billing-system
+#      config:
+#        platform: linux
+#        image_resource:
+#          type: docker-image
+#          source:
+#            repository: pivotalservices/pcf-usage-tools
+#            tag: "latest"
+#        inputs:
+#          - name: pipeline-scripts
+#          - name: file-repository
+#        run:
+#          path: sh
+#          args:
+#          - -exc
+#          - |
+#            #!/bin/bash
+#            set -e
+#            echo "This is a place holder for the code to read the report file from the file repository and feed it to a billing system"
+#            echo "JSON Report file URL from the repository:"
+#            cat ./file-repository/url
+#            echo "Report file version(timestamp of creation in seconds):"
+#            cat ./file-repository/version
+#            echo "File list available to be used by this job/task:"
+#            ls -la file-repository
+#
+#
+#    - put: send-email
+#      params:
+#        to: [ {{email-to}} ]
+#        subject: ./email-text/email-subject.txt
+#        body: ./email-text/email-body.txt
+#
+#    on_failure:
+#      put: send-email
+#      params:
+#        to: [ {{email-to}} ]
+#        subject: ./email-text/email-subject-failure.txt
+#        body: ./email-text/email-body-failure.txt
